name: Deploy SAM Template

on:
  workflow_dispatch:  # Manually trigger the workflow
    inputs:
      environment:
        description: What AWS environment to deploy to
        required: true
        type: string
        default: DEV
      aws-region:
        description: What AWS region to deploy to
        required: false
        type: string
        default: us-east-2
      s3-bucket:
        description: What AWS S3-bucket to place package in
        required: false
        type: string
        default: samtestbucket22
      parameter-overrides:
        description: Parameter overrides for this deploysment (space-delimited, key=value)
        required: false
        type: string
        default: ''
      git-ref:
        description: Git ref (branch/tag) to deploy
        required: true
        type: string
      source_root:
        description: Where the PYTHON source code files reside in this repo
        required: false
        type: string
        default: .
      python-version:
        description: What version of Python to use
        required: false
        type: string
        default: '3.11'
      pre-script:
        description: A custom script that might be needed before deploying
        required: false
        type: string
        default: ''

jobs:
  deploy:
    name: Deploy SAM Template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Change this to your desired AWS region

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Build SAM application
        run: sam build --template samtemplate.yml

      - name: Package SAM application
        run: sam package --output-template-file packaged.yaml --s3-bucket samtestbucket22  # Change this to your S3 bucket name

      - name: Deploy SAM application
        run: sam deploy --stack-name samdeploymenttest --template-file packaged.yaml --capabilities CAPABILITY_IAM
