name: Deploy SAM Template

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  deploy:
    name: Deploy SAM Template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Change this to your desired AWS region

        env:
          AWS_SDK_LOAD_CONFIG: 1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Build SAM application
        run: sam build --template samtemplate.yml

      - name: Package SAM application
        run: sam package --output-template-file packaged.yaml --s3-bucket samtestbucket22  # Change this to your S3 bucket name

      - name: Deploy SAM application
        run: sam deploy --stack-name samdeploymenttest --template-file packaged.yaml --capabilities CAPABILITY_IAM
